src_mask_label_pattern: "Rellis_3D/Rellis_3D_pylon_camera_node_label_id/**/*.png"
keep_subdir_levels: 3
dst_mask_id_root: "AWF_FreeSeg_label/Rellis_3D/label_id"
dst_mask_color_root: "AWF_FreeSeg_label/Rellis_3D/label_color"
overwrite_existing: false
label_to_id_mapping:
  0:  0   # void    -> undefined
  1:  2   # dirt    -> drivable
  3:  2   # grass   -> drivable
  4:  1   # tree    -> non-drivable
  5:  1   # pole    -> non-drivable
  6:  1   # water   -> non-drivable
  7:  1   # sky     -> non-drivable
  8:  1   # vehicle -> non-drivable
  9:  1   # object  -> non-drivable
  10: 2   # asphalt -> drivable
  12: 1   # building-> non-drivable
  15: 1   # log     -> non-drivable
  17: 1   # person  -> non-drivable
  18: 1   # fence   -> non-drivable
  19: 1   # bush    -> non-drivable
  23: 2   # concrete-> drivable
  27: 1   # barrier -> non-drivable
  31: 2   # puddle  -> drivable
  33: 2   # mud     -> drivable
  34: 2   # rubble  -> drivable