id_to_color_mapping:
  0:  [61, 184, 255]     # sky                    -> light blue
  1:  [0, 0, 0]          # background_objects     -> black
  2:  [255, 28, 145]     # infrastructure_objects -> light pink
  3:  [176, 20, 101]     # building               -> dark pink
  4:  [255, 61, 61]      # vulnerable_living      -> red
  5:  [255, 190, 61]     # small_mobile_vehicle   -> light orange
  6:  [255, 116, 61]     # large_mobile_vehicle   -> dark orange
  7:  [170, 170, 170]    # paved_road             -> light gray
  8:  [120, 120, 120]    # gravel                 -> gray
  9:  [80, 80, 80]       # rock                   -> dark gray
  10: [54, 235, 56]      # small_vegatation       -> light green
  11: [32, 133, 33]      # large_vegatation       -> dark green
  12: [166, 126, 54]     # dirt                   -> brown
  13: [61, 93, 255]      # water                  -> blue
  14: [36, 54, 140]      # puddle                 -> dark blue
  15: [220, 220, 220]    # snow                   -> snow