id_to_color_mapping:
  0: [61, 184, 255]     # sky                  -> light blue
  1: [61, 93, 255]      # background_objects   -> dark blue
  2: [255, 28, 145]     # forground_objects    -> pink
  3: [255, 61, 61]      # vulnerable_living    -> red
  4: [255, 190, 61]     # small_mobile_vehicle -> light orange
  5: [255, 116, 61]     # large_mobile_vehicle -> dark orange
  6: [0, 255, 220]      # road                 -> cyan


