src_mask_label_pattern: "OFFSED/devkit_offsed/SegmentationClass/*.png"
exclude_patterns: []
keep_subdir_levels: 1
dst_mask_id_root: "AWF_FreeSeg_label/OFFSED/label_id"
dst_mask_color_root: "AWF_FreeSeg_label/OFFSED/label_color"
overwrite_existing: true
color_thresh: 3
label_to_id_mapping:
  "[0, 0, 0]":       1   # background           -> non-drivable
  "[70, 70, 70]":    1   # building             -> non-drivable
  "[99, 128, 52]":   1   # bush                 -> non-drivable
  "[0, 0, 90]":      1   # camper               -> non-drivable
  "[0, 0, 142]":     1   # car                  -> non-drivable
  "[184, 151, 51]":  1   # crops                -> non-drivable
  "[81, 0, 81]":     2   # drivable dirt        -> drivable
  "[128, 64, 128]":  2   # drivable pavement    -> drivable
  "[0, 60, 100]":    1   # excavator            -> non-drivable
  "[24, 226, 31]":   2   # grass                -> drivable
  "[180, 165, 180]": 1   # guard rail           -> non-drivable
  "[44, 231, 215]":  1   # held object          -> non-drivable
  "[175, 44, 190]":  1   # nondrivable dirt     -> non-drivable
  "[244, 35, 232]":  1   # nondrivable pavement -> non-drivable
  "[255, 0, 0]":     1   # obstacle             -> non-drivable
  "[209, 43, 77]":   1   # person               -> non-drivable
  "[70, 130, 180]":  1   # sky                  -> non-drivable
  "[107, 142, 35]":  1   # tree                 -> non-drivable
  "[0, 0, 70]":      1   # truck                -> non-drivable
  "[102, 102, 156]": 1   # wall                 -> non-drivable