src_mask_label_pattern: "Goose/goose_2d_train/labels/train/**/**_labelids.png"
exclude_patterns: []
keep_subdir_levels: 2
dst_mask_id_root: "AWF_FreeSeg_label/Goose/label_id"
dst_mask_color_root: "AWF_FreeSeg_label/Goose/lable_color"
overwrite_existing: true
color_thresh: 3
label_to_id_mapping:
  0:  0   # undefined          -> undefined
  1:  1   # traffic_cone       -> non-drivable
  2:  2   # snow               -> drivable
  3:  2   # cobble             -> drivable
  4:  1   # obstacle           -> non-drivable
  5:  2   # leaves             -> drivable
  6:  1   # street_light       -> non-drivable
  7:  2   # bikeway            -> drivable
  8:  1   # ego_vehicle        -> non-drivable
  9:  1   # pedestrian_crossing-> non-drivable
  10: 1   # road_block         -> non-drivable
  11: 2   # road_marking       -> drivable
  12: 1   # car                -> non-drivable
  13: 1   # bicycle            -> non-drivable
  14: 1   # person             -> non-drivable
  15: 1   # bus                -> non-drivable
  16: 1   # forest             -> non-drivable
  17: 1   # bush               -> non-drivable
  18: 2   # moss               -> drivable
  19: 1   # traffic_light      -> non-drivable
  20: 1   # motorcycle         -> non-drivable 
  21: 1   # sidewalk           -> non-drivable
  22: 1   # curb               -> non-drivable
  23: 2   # asphalt            -> drivable
  24: 2   # gravel             -> drivable
  25: 1   # boom_barrier       -> non-drivable
  26: 1   # rail_track         -> non-drivable
  27: 1   # tree_crown         -> non-drivable
  28: 1   # tree_trunk         -> non-drivable
  29: 1   # debris             -> non-drivable
  30: 1   # crops              -> non-drivable
  31: 2   # soil               -> drivable
  32: 1   # rider              -> non-drivable
  33: 1   # animal             -> non-drivable
  34: 1   # truck              -> non-drivable
  35: 1   # on_rails           -> non-drivable
  36: 1   # caravan            -> non-drivable
  37: 1   # trailer            -> non-drivable
  38: 1   # building           -> non-drivable
  39: 1   # wall               -> non-drivable
  40: 1   # rock               -> non-drivable
  41: 1   # fence              -> non-drivable
  42: 1   # guard_rail         -> non-drivable
  43: 1   # bridge             -> non-drivable
  44: 1   # tunnel             -> non-drivable
  45: 1   # pole               -> non-drivable
  46: 1   # traffic_sign       -> non-drivable
  47: 1   # misc_sign          -> non-drivable
  48: 1   # barrier_tape       -> non-drivable
  49: 1   # kick_scooter       -> non-drivable
  50: 2   # low_grass          -> drivable
  51: 2   # high_grass         -> drivable
  52: 2   # scenery_vegetation -> drivable
  53: 1   # sky                -> non-drivable
  54: 2   # water              -> drivable
  55: 1   # wire               -> non-drivable 
  56: 1   # outlier            -> non-drivable 
  57: 1   # heavy_machinery    -> non-drivable 
  58: 1   # container          -> non-drivable 
  59: 1   # hedge              -> non-drivable 
  60: 1   # barrel             -> non-drivable 
  61: 1   # pipe               -> non-drivable 
  62: 2   # tree_root          -> drivable 
  63: 1   # military_vehicle   -> non-drivable 