src_image_pattern: "Goose/**/**_vis.png"
src_gt_mask_pattern: "Goose/**/**_labelids.png"
exclude_patterns: ["Goose/goose_2d_test/**/**.png"]
dst_image_dir: "AORAS/ObjectSeg/Goose/Goose/images"
dst_gt_mask_dir: "AORAS/ObjectSeg/Goose/Goose/gt_masks"
overwrite_existing: false
color_thresh: 3
label_to_id_mapping:
  0:  1   # undefined          -> background_objects
  1:  2   # traffic_cone       -> forground_objects
  2:  1   # snow               -> background_objects
  3:  1   # cobble             -> background_objects
  4:  2   # obstacle           -> forground_objects
  5:  1   # leaves             -> background_objects
  6:  2   # street_light       -> forground_objects
  7:  1   # bikeway            -> background_objects
  8:  1   # ego_vehicle        -> background_objects
  9:  2   # pedestrian_crossing-> forground_objects
  10: 2   # road_block         -> forground_objects
  11: 6   # road_marking       -> road
  12: 5   # car                -> large_mobile_vehicle
  13: 4   # bicycle            -> small_mobile_vehicle
  14: 3   # person             -> vulnerable_living
  15: 5   # bus                -> large_mobile_vehicle
  16: 1   # forest             -> background_objects
  17: 1   # bush               -> background_objects
  18: 1   # moss               -> background_objects
  19: 2   # traffic_light      -> forground_objects
  20: 4   # motorcycle         -> small_mobile_vehicle
  21: 1   # sidewalk           -> background_objects
  22: 1   # curb               -> background_objects
  23: 6   # asphalt            -> road
  24: 1   # gravel             -> background_objects
  25: 2   # boom_barrier       -> forground_objects
  26: 1   # rail_track         -> background_objects
  27: 1   # tree_crown         -> background_objects
  28: 1   # tree_trunk         -> background_objects
  29: 1   # debris             -> background_objects
  30: 1   # crops              -> background_objects
  31: 1   # soil               -> background_objects
  32: 3   # rider              -> vulnerable_living
  33: 3   # animal             -> vulnerable_living
  34: 5   # truck              -> large_mobile_vehicle
  35: 1   # on_rails           -> background_objects
  36: 5   # caravan            -> large_mobile_vehicle
  37: 5   # trailer            -> large_mobile_vehicle
  38: 1   # building           -> background_objects
  39: 1   # wall               -> background_objects
  40: 1   # rock               -> background_objects
  41: 2   # fence              -> forground_objects
  42: 2   # guard_rail         -> forground_objects
  43: 1   # bridge             -> background_objects
  44: 1   # tunnel             -> background_objects
  45: 2   # pole               -> forground_objects
  46: 2   # traffic_sign       -> forground_objects
  47: 2   # misc_sign          -> forground_objects
  48: 2   # barrier_tape       -> forground_objects
  49: 4   # kick_scooter       -> small_mobile_vehicle
  50: 1   # low_grass          -> background_objects
  51: 1   # high_grass         -> background_objects
  52: 1   # scenery_vegetation -> background_objects
  53: 0   # sky                -> sky
  54: 1   # water              -> background_objects
  55: 2   # wire               -> forground_objects
  56: 1   # outlier            -> background_objects
  57: 5   # heavy_machinery    -> large_mobile_vehicle
  58: 1   # container          -> background_objects
  59: 1   # hedge              -> background_objects
  60: 2   # barrel             -> forground_objects
  61: 2   # pipe               -> forground_objects
  62: 1   # tree_root          -> background_objects
  63: 5   # military_vehicle   -> large_mobile_vehicle