src_image_pattern: "CaSSeD/CaSSed_Dataset/Real_World_data/**/raw_images/*.png"
src_gt_mask_pattern: "CaSSeD/CaSSed_Dataset/Real_World_data/**/annotations/*.png"
exclude_patterns:  
  - "CaSSeD/CaSSed_Dataset/Real_World_data/Test/*"
  - "CaSSeD/CaSSed_Dataset/Real_World_data/Train/*"
dst_image_dir: "AORAS/ObjectSeg/CaSSeD/CaSSeD/images"
dst_gt_mask_dir: "AORAS/ObjectSeg/CaSSeD/CaSSeD/gt_masks"
overwrite_existing: false
color_thresh: 3
label_to_id_mapping:
  "[155, 155, 155]":  12  # Smooth Trail     -> dirt
  "[139, 87, 42]":    12  # Rough Trail      -> dirt
  "[209, 255, 158]":  10  # Small Vegetation -> small_vegatation
  "[59, 93, 4]":      11  # Forest           -> large_vegatation
  "[184, 20, 124]":   2   # Obstacle         -> infrastructure_objects
  "[74, 144, 226]":   0   # Sky              -> sky