src_image_pattern: "Rellis_3D/Rellis_3D_pylon_camera_node/**/*.jpg"
src_gt_mask_pattern: "Rellis_3D/Rellis_3D_pylon_camera_node_label_id/**/*.png"
exclude_patterns: []
dst_image_dir: "AORAS/ObjectSeg/Rellis_3D/Rellis_3D/images"
dst_gt_mask_dir: "AORAS/ObjectSeg/Rellis_3D/Rellis_3D/gt_masks"
overwrite_existing: false
color_thresh: 3
label_to_id_mapping:
  0:  0   # void    -> undefined
  1:  12  # dirt    -> dirt
  3:  10  # grass   -> small vegatation
  4:  11  # tree    -> large vegatation
  5:  2   # pole    -> infrastructure_objects
  6:  13  # water   -> water
  7:  0   # sky     -> sky
  8:  5   # vehicle -> small_mobile_vehicle
  9:  2   # object  -> infrastructure_objects
  10: 7   # asphalt -> paved road
  12: 3   # building-> building
  15: 11  # log     -> large vegatation
  17: 4   # person  -> vulnerable_living
  18: 2   # fence   -> infrastructure_objects
  19: 11  # bush    -> large vegatation
  23: 7   # concrete-> paved road
  27: 2   # barrier -> infrastructure_objects
  31: 14  # puddle  -> puddle
  33: 12  # mud     -> dirt
  34: 8   # rubble  -> gravel