_target_: datamodule.goose_dataset.GooseDataModule 
root: /home/autokarthik/autoware.off-road/goose-dataset    
batch_size: 4
num_workers: 8
num_classes: 12
img_size: [512, 512]   
scale_base: [2048, 512]
ratio_range: [0.5, 2.0]
mean: [123.675, 116.28, 103.53]
std:  [58.395,  57.12,  57.375]
