label_map:
  0: 0     # Background -> Background
  1: 0     # Dirt -> Background
  2: 1     # Grass -> Vegetation
  3: 1     # Bush -> Vegetation
  4: 2     # Tree -> Tree
  5: 3     # Building -> Man-made
  6: 3     # Vehicle -> Man-made
  7: 4     # Person -> Human
  8: 5     # Sky -> Sky

